//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinikWPF.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int Id_Records { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> Id_Owners { get; set; }
        public Nullable<int> Id_Veterenar { get; set; }
        public Nullable<int> Id_Animals { get; set; }
        public string Desc_Disease { get; set; }
        public string Desc_Treatment { get; set; }
        public string Desc_Diagnoz { get; set; }
    
        public virtual Animals Animals { get; set; }
        public virtual Owners Owners { get; set; }
        public virtual Users Users { get; set; }
    }
}
